### ISSUE TITLE
版主能否编译成exe，方便下载下吗？感谢

### ISSUE THREAD

**Issue by HeliusHao** [chenall/tightvnc#1]

**Comment by chenall** [comment]
[Release_x86_Bin.zip](https://github.com/chenall/tightvnc/files/6451049/Release_x86_Bin.zip)
[Release_x64_Bin.zip](https://github.com/chenall/tightvnc/files/6451050/Release_x64_Bin.zip)

**Comment by HeliusHao** [comment]
感谢 chenall 版主

**Comment by chenall** [comment]
https://ci.appveyor.com/project/chenall/tightvnc 这里可以下载,今天看到官网已经更新了,顺便就更到 2.8.59 版本

**Comment by HeliusHao** [comment]
> https://ci.appveyor.com/project/chenall/tightvnc 这里可以下载,今天看到官网已经更新了,顺便就更到 2.8.59 版本

真及时啊，还带着热乎劲呢，感谢！

**Comment by HeliusHao** [comment]
楼主好，tightvnc 新出了个软件，可以一屏多看窗口
地址是这个 https://mightyviewer.com/?mvasrc=about&mvaver=1.2.3
这个软件试用是30天。可以在安装前把系统日期往后调整后再安装，这样就可以多用很长时间，不知道您这边能否patch个sn授权呢，有的话，也可以发我一个吗，感谢，你可以试试，挺好用的
