### ISSUE TITLE
Del

### ISSUE THREAD

**Issue by HeliusHao** [chenall/tightvnc#10]

**Comment by chenall** [comment]
我抽空更新一下  ^_^

**Comment by chenall** [comment]
已更新

**Comment by HeliusHao** [comment]
收到，感谢C大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 晚上8:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenall/tightvnc] C大，2.8.84版本已发布，求更新成您的定制版，谢谢。 (Issue #10)




 
已更新

**Comment by HeliusHao** [comment]
C大，我下载了您修改后的源码，又下载了个vs2019进行编译，提示3种错误，您知道如何解决吗？谢谢，能让我顺利编译成功吗？
![eroor1](https://github.com/user-attachments/assets/ff54f603-9f3a-421b-be69-b67d5b5fdd7c)
![eroor2](https://github.com/user-attachments/assets/d08b194f-3923-4e78-ab93-0e1b8a3e5b83)
