### ISSUE TITLE
C大，我用您的代码，拿vs2019编译，没成功，出现以下错误，可以教教小弟，如何能编译成功吗？谢谢

### ISSUE THREAD

**Issue by HeliusHao** [chenall/tightvnc#12]
[error.txt](https://github.com/user-attachments/files/16483117/error.txt)

**Comment by HeliusHao** [comment]
C大，我用您的源码，用vs2015编译Release，有4个错误，没成功，方便教下小弟排错，可以吗？万分谢谢，
[error 20240824-2204.txt](https://github.com/user-attachments/files/16487786/error.20240824-2204.txt)
我QQ：14378005

**Comment by chenall** [comment]
我用的是 tightvnc2019.sln
编译的话需要用 git 命令下载源码
然后合并最新版本代码
```
git clone -q -n --branch=v2.8.84 https://github.com/chenall/tightvnc.git C:\projects\tightvnc
git merge origin/upstream
```

**Comment by HeliusHao** [comment]
C大
您能发给我一个合并好的压缩包发我下吗，我实在是搞不定git，谢谢

我邮箱 ***@***.***



***@***.***
 
发件人： chenall
发送时间： 2024-08-09 10:36
收件人： chenall/tightvnc
抄送： Helius; Author
主题： Re: [chenall/tightvnc] C大，我用您的代码，拿vs2019编译，没成功，出现以下错误，可以教教小弟，如何能编译成功吗？谢谢 (Issue #12)
我用的是 tightvnc2019.sln
编译的话需要用 git 命令下载源码
然后合并最新版本代码
git clone -q -n --branch=v2.8.84 https://github.com/chenall/tightvnc.git C:\projects\tightvnc
git merge origin/upstream

**Comment by HeliusHao** [comment]
C大搞定了，可以编译了
现在有个问题，但是我不知道如何修改
我想把配置文件修改成一个固定的名字，不用跟exe文件名相同
比如想把配置文件改成  VNC_config.ini


  }
  //检测是否有INI配置文件
  GetModuleFileName(NULL, ConfigFile, MAX_PATH);
  size_t n = lstrlen(ConfigFile);
  lstrcpyn(&ConfigFile[n - 3], L"ini", 4);
  if (GetFileAttributes(ConfigFile) == INVALID_FILE_ATTRIBUTES) {
	  ConfigFile[0] = 0;
  }
}

您这段代码，我改了半天，也不会改，原先学过c#，但是不会C++，您方便告诉我下，如何修改吗？谢谢
