### ISSUE TITLE
C大，能弄个2.8.63版本吗？分享个下载，谢谢

### ISSUE THREAD

**Issue by HeliusHao** [chenall/tightvnc#3]

**Comment by chenall** [comment]
x64
https://ci.appveyor.com/project/chenall/tightvnc/build/job/34qiy7ommbyb0s43/artifacts
x86
https://ci.appveyor.com/project/chenall/tightvnc/build/job/8c535p7plpt2xers/artifacts

**Comment by HeliusHao** [comment]
谢谢C大。



***@***.***
 
发件人： chenall
发送时间： 2021-11-15 15:59
收件人： chenall/tightvnc
抄送： Helius; Author
主题： Re: [chenall/tightvnc] C大，能弄个2.8.63版本吗？分享个下载，谢谢 (Issue #3)
x64
https://ci.appveyor.com/project/chenall/tightvnc/build/job/34qiy7ommbyb0s43/artifacts
x86
https://ci.appveyor.com/project/chenall/tightvnc/build/job/8c535p7plpt2xers/artifacts

**Comment by HeliusHao** [comment]
老大，能弄个最新版的去图片ini版本吗





TightVNC 2.8.78



万分感谢。




Helius
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        ***@***.***"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 下午4:21
***@***.***&gt;;

主题:&nbsp;Re: Re: [chenall/tightvnc] C大，能弄个2.8.63版本吗？分享个下载，谢谢 (Issue #3)



 谢谢C大。
 


 ***@***.***


 &nbsp;
发件人：&nbsp;chenall
发送时间：&nbsp;2021-11-15 15:59
收件人：&nbsp;chenall/tightvnc
抄送：&nbsp;Helius; Author
主题：&nbsp;Re: [chenall/tightvnc] C大，能弄个2.8.63版本吗？分享个下载，谢谢 (Issue #3)




 
x64
 https://ci.appveyor.com/project/chenall/tightvnc/build/job/34qiy7ommbyb0s43/artifacts
 x86
 https://ci.appveyor.com/project/chenall/tightvnc/build/job/8c535p7plpt2xers/artifacts
