### ISSUE TITLE
TightVNC 2.8.81

### ISSUE THREAD

**Issue by HeliusHao** [chenall/tightvnc#6]

**Comment by chenall** [comment]
已经更新上传

**Comment by HeliusHao** [comment]
谢谢，真是太高效了，真是会者不难，难者不会啊。
万分感谢。



***@***.***
 
From: chenall
Date: 2023-05-18 16:24
To: chenall/tightvnc
CC: Helius; Author
Subject: Re: [chenall/tightvnc] TightVNC 2.8.81 (Issue #6)
Closed #6 as completed.

**Comment by QQ2017** [comment]
> 已经更新上传

发现有些修改会覆盖官方的BUG修复，我认为版主应该重新检查修改的代码，基于官方代码重新修改

比如下面的代码右侧是官方相同版本的代码（tightvnc-2.8.81-gpl），很明显此处是做了更多判断，ini版本把这块去掉了：
![image](https://github.com/chenall/tightvnc/assets/23667705/478f28bf-b31e-4c71-92d8-c9c77b9438cd)

后面发现版主的代码版本似乎是 tightvnc-2.8.79
![image](https://github.com/chenall/tightvnc/assets/23667705/c6a41881-9733-4848-8c41-99f6af9b13d2)

**Comment by HeliusHao** [comment]
C大，您更新完的，在哪里下更新包？




***@***.***
 
From: 27℃
Date: 2023-06-02 15:32
To: chenall/tightvnc
CC: Helius; Author
Subject: Re: [chenall/tightvnc] TightVNC 2.8.81 (Issue #6)
已经更新上传
发现有些修改会覆盖官方的BUG修复，比如下面的代码右侧是官方相同版本的代码，很明显此处是做了更多判断，ini版本把这块去掉了：

**Comment by QQ2017** [comment]
他应该是更新的二进制文件，对比了下修改处，似乎修改的也不多，有空可以自己改下。。

**Comment by HeliusHao** [comment]
> 他应该是更新的二进制文件，对比了下修改处，似乎修改的也不多，有空可以自己改下。。

说实话，不会改。^_^

**Comment by chenall** [comment]
> > 已经更新上传
> 
> 发现有些修改会覆盖官方的BUG修复，我认为版主应该重新检查修改的代码，基于官方代码重新修改
> 
> 比如下面的代码右侧是官方相同版本的代码（tightvnc-2.8.81-gpl），很明显此处是做了更多判断，ini版本把这块去掉了： ![image](https://user-images.githubusercontent.com/23667705/242817678-478f28bf-b31e-4c71-92d8-c9c77b9438cd.png)
> 
> 后面发现版主的代码版本似乎是 tightvnc-2.8.79 ![image](https:user-images.githubusercontent.com/23667705/242821219-c6a41881-9733-4848-8c41-99f6af9b13d2.png)

你对比的是哪个版本?  upstream 是这官方的版本
main 是修改的(不经常更新)

编译时要把 upstream 的版本合并到 main 下再编译.

正常情况下我只更新 upstream 的版本.

有需要的可以自己合并一下就是最新的修改版本代码.

**Comment by chenall** [comment]
https://github.com/chenall/tightvnc/issues/5#issuecomment-1515999186
